server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/foodshare_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Divya13!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true